### ISSUE TITLE
Make error

### ISSUE THREAD

**Issue by iw0red** [g4klx/ircDDBGateway#48]
Hi,
I tried to compile ircddbgateway software on this machine:
Linux sserano 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux

But I had this error:

g++ -O2 -Wall -I/usr/lib/x86_64-linux-gnu/wx/include/base-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -pthread -DLOG_DIR='"/var/log"' -DCONF_DIR='"/etc"' -DDATA_DIR='"/usr/share/ircddbgateway"' -I../Common -c -o AddressTextCtrl.o AddressTextCtrl.cpp
In file included from AddressTextCtrl.h:24,
                 from AddressTextCtrl.cpp:19:
RestrictedTextCtrl.h:24:47: error: expected class-name before '{' token
 class CRestrictedTextCtrl : public wxTextCtrl {
                                               ^
RestrictedTextCtrl.h:26:77: error: 'wxPoint' does not name a type; did you mean 'wxJoin'?
  CRestrictedTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos, const wxSize& size, long style, const wxString& wantedChars);
                                                                             ^~~~~~~
                                                                             wxJoin
RestrictedTextCtrl.h:26:97: error: 'wxSize' does not name a type; did you mean 'wxTimer'?
  CRestrictedTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos, const wxSize& size, long style, const wxString& wantedChars);
                                                                                                 ^~~~~~
                                                                                                 wxTimer
In file included from AddressTextCtrl.cpp:19:
AddressTextCtrl.h:31:74: error: 'wxPoint' does not name a type; did you mean 'wxJoin'?
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                          ^~~~~~~
                                                                          wxJoin
AddressTextCtrl.h:31:114: error: 'wxSize' does not name a type; did you mean 'wxTimer'?
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                                                                  ^~~~~~
                                                                                                                  wxTimer
AddressTextCtrl.h:31:89: error: 'wxDefaultPosition' was not declared in this scope
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                                         ^~~~~~~~~~~~~~~~~
AddressTextCtrl.h:31:89: note: suggested alternative: 'wxDefaultListKey'
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                                         ^~~~~~~~~~~~~~~~~
                                                                                         wxDefaultListKey
In file included from AddressTextCtrl.cpp:19:
AddressTextCtrl.h:31:129: error: 'wxDefaultSize' was not declared in this scope
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                                                                                 ^~~~~~~~~~~~~
AddressTextCtrl.h:31:129: note: suggested alternative: 'wxDefaultListKey'
  CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize, long style = 0L);
                                                                                                                                 ^~~~~~~~~~~~~
                                                                                                                                 wxDefaultListKey
AddressTextCtrl.cpp:21:91: error: 'wxPoint' does not name a type; did you mean 'wxJoin'?
 CAddressTextCtrl::CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos, const wxSize& size, long style) :
                                                                                           ^~~~~~~
                                                                                           wxJoin
AddressTextCtrl.cpp:21:111: error: 'wxSize' does not name a type; did you mean 'wxTimer'?
 CAddressTextCtrl::CAddressTextCtrl(wxWindow* parent, int id, const wxString& value, const wxPoint& pos, const wxSize& size, long style) :
                                                                                                               ^~~~~~
                                                                                                               wxTimer
make[1]: *** [Makefile:13: AddressTextCtrl.o] Error 1
make[1]: Leaving directory '/root/ircDDBGateway/GUICommon'
make: *** [Makefile:54: GUICommon/GUICommon.a] Error 2

Thanks.
73 Marco IW0RED.

**Comment by fabianfrz** [comment]
I can confirm that the code compiles with wx 3.2. Please try to update wxwidgets
